# Generated by Django 5.1.6 on 2025-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('duree_contrat', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nom_employeur', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('metier', models.CharField(max_length=255)),
            ],
        ),
    ]
